# Generated by Django 4.1.5 on 2023-01-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
